baseURL: 'http://banksyx.github.io/'
languageCode: en-us
title: Banksyx's Blog
theme: hugo-PaperMod

params:
    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
            url: "/archive"
            - name: Github
            url: "https://github.com/"

    socialIcons: # optional
        - name: "<platform>"
            url: "<link>"
        - name: "<platform 2>"
            url: "<link2>"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

paginate: 10    # the number of posts in each page

params:
    ShowShareButtons: true
params:
    ShowCodeCopyButtons: true
params:
    comments: true